name: Automation Plus Workflow

on:
  issues:
    types: [opened, edited, closed]

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Automation Plus
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
