# NOTE: If you encounter an error that says "Dependency review is not supported on this repository",
# please ensure that the Dependency graph and GitHub Advanced Security are enabled on your private repository.
# You can enable these settings at https://github.com/cubxxw/chat/settings/security_analysis
# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3