# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check for Enabled Features'
        run: |
          if [ -z "$ENABLE_DEPENDENCY_GRAPH" ] || [ -z "$ENABLE_ADVANCED_SECURITY" ]; then
            echo "Error: Dependency graph and GitHub Advanced Security features are not enabled. Please enable these features in your repository settings." >&2
            exit 1
          fi
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3