# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Check Repository Settings'
        uses: actions/github-script@v5
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            if (!repo.data.has_issues || !repo.data.has_wiki) {
              core.setFailed('Dependency graph and GitHub Advanced Security must be enabled on the repository.')
            }
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3